"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yEVYMlSPKbA
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { updateTerminalFromLines } from "@/actions/update-terminal";
import { PresetOptions } from "@/presets";
import { useState } from "react";

export function Terminal() {
  const [preview1, setPreview1] = useState("");
  const [preview2, setPreview2] = useState("");
  return (
    <>
      <header className="w-full px-4 py-8 md:px-12 lg:px-16 xl:px-24">
        <div className="container mx-auto">
          <h1 className="text-4xl font-bold text-center">FUJITSU DISPLAY</h1>
        </div>
      </header>
      <main className="md:flex md:justify-between w-full px-4 py-8 md:px-12 lg:px-16 xl:px-24">
        <div className="md:w-1/2 container mx-auto">
          <Card className="w-full max-w-2xl mx-auto p-8 space-y-4">
            <div className="flex flex-col items-center space-y-4 text-center">
              <h2 className="text-2xl font-bold">
                Welcome to our one-page application
              </h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                Please input your data below
              </p>
            </div>
            <form
              action={updateTerminalFromLines}
              method="POST"
              className="space-y-2"
            >
              <Input
                name="line1"
                className="w-full px-3 py-2 border border-gray-300 rounded-md"
                placeholder="Enter first line"
                type="text"
                onChange={(e) => setPreview1(e.target.value)}
              />
              <Input
                name="line2"
                className="w-full px-3 py-2 border border-gray-300 rounded-md"
                placeholder="Enter second line"
                type="text"
                onChange={(e) => setPreview2(e.target.value)}
              />
              <Button className="w-full h-12 bg-blue-500 text-white">
                Accept
              </Button>
            </form>
            <p>Or choose from the dropdown below</p>
            <form
              className="space-y-2"
              action={updateTerminalFromLines}
              method="POST"
            >
              <select
                name="cannedResponses"
                className="text-black w-full px-3 py-2 border border-gray-300 rounded-md"
                onChange={(e) => {
                  const [l1, l2] = e.target.value.split(",");
                  setPreview1(l1);
                  setPreview2(l2);
                }}
              >
                <option value="">Select...</option>
                {PresetOptions.map((option) => (
                  <option key={option[0] + option[1]} value={option}>
                    {`TOP: ${option[0]} BOTTOM: ${option[1]}`}
                  </option>
                ))}
              </select>
              <Button className="w-full h-12 bg-blue-500 text-white">
                Accept
              </Button>
            </form>
          </Card>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
            Or choose from the dropdown below
          </p>
        </div>
        <div className="md:w-1/2 container mx-auto md:mt-0 mt-8 md:ml-8">
          <Card className="w-full max-w-2xl mx-auto p-8 space-y-4 bg-black text-green-500">
            <div className="text-center">
              <h2 className="text-2xl font-bold">Preview</h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400 font-mono">
                {!preview1 && preview2
                  ? "Your input will be rendered here."
                  : null}
                {preview1}
                <br />
                {preview2}
              </p>
            </div>
          </Card>
        </div>
      </main>
      <footer className="w-full px-4 py-8 md:px-12 lg:px-16 xl:px-24">
        <div className="container mx-auto">
          <div className="flex justify-center items-center" />
        </div>
      </footer>
    </>
  );
}
